packages:
  - 'apps/*'
  - 'forge/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - vue-demi

confirmModulesPurge: false
allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': true
  esbuild: true
  simple-git-hooks: true
  vue-demi: true
