// Drizzle 的稳定聚合入口：新增 Schema 分片必须在此登记，避免迁移或运行时遗漏表定义。
export * from './schema/common.schema.js'
export * from './schema/roles.schema.js'
export * from './schema/departments.schema.js'
export * from './schema/users.schema.js'
export * from './schema/positions.schema.js'
export * from './schema/authorization.schema.js'
export * from './schema/menus.schema.js'
export * from './schema/auth.schema.js'
export * from './schema/dictionaries.schema.js'
export * from './schema/api-logs.schema.js'
