/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthData: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        HealthResponse: {
            /** @enum {integer} */
            status: 0;
            data: components["schemas"]["HealthData"];
            err?: string;
        };
        ErrorResponse: {
            status: number;
            err: string;
        };
        PaginationRequest: {
            /**
             * @description 1-based page number; defaults to 1 when omitted
             * @example 1
             */
            pageNum?: number;
            /**
             * @description Number of items per page; defaults to 10 when omitted
             * @example 10
             */
            pageSize?: number;
        };
        PaginationResponse: {
            status: number;
            list: unknown[];
            total: number;
            err?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Global HTTP failure; business APIs only use HTTP 401, 404, or 500 */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
