/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create a user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a user */
        put: operations["updateUser"];
        post?: never;
        /** Soft-delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["listRoles"];
        put?: never;
        /** Create a role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a role */
        put: operations["updateRole"];
        post?: never;
        /** Soft-delete a role */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List menus */
        get: operations["listMenus"];
        put?: never;
        /** Create a menu */
        post: operations["createMenu"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a menu */
        put: operations["updateMenu"];
        post?: never;
        /** Soft-delete a menu */
        delete: operations["deleteMenu"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dictionaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dictionary entries */
        get: operations["listDictionaries"];
        put?: never;
        /** Create a dictionary entry */
        post: operations["createDictionary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dictionaries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a dictionary entry */
        put: operations["updateDictionary"];
        post?: never;
        /** Soft-delete a dictionary entry */
        delete: operations["deleteDictionary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditFields: {
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            createdBy: number;
            /** Format: date-time */
            updatedAt: string;
            updatedBy: number;
        };
        HealthData: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        HealthResponse: {
            /** @enum {integer} */
            status: 0;
            data: components["schemas"]["HealthData"];
        };
        ErrorResponse: {
            status: number;
            err: string;
        };
        EmptySuccessResponse: {
            /** @enum {integer} */
            status: 0;
        };
        IdData: {
            id: number;
        };
        IdResponse: {
            /** @enum {integer} */
            status: 0;
            data: components["schemas"]["IdData"];
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        CurrentUser: {
            id: number;
            username: string;
            displayName: string;
            roles: string[];
        };
        CurrentUserResponse: {
            /** @enum {integer} */
            status: 0;
            data: components["schemas"]["CurrentUser"];
        };
        UserSummary: components["schemas"]["AuditFields"] & {
            id: number;
            username: string;
            displayName: string;
            /** Format: email */
            email: string;
            enabled: boolean;
            roleIds: number[];
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        UserCreateRequest: {
            username: string;
            displayName: string;
            /** Format: email */
            email: string;
            password: string;
            enabled: boolean;
            roleIds: number[];
        };
        UserUpdateRequest: {
            displayName: string;
            /** Format: email */
            email: string;
            password?: string;
            enabled: boolean;
            roleIds: number[];
        };
        UserPageResponse: {
            /** @enum {integer} */
            status: 0;
            list: components["schemas"]["UserSummary"][];
            total: number;
        };
        RoleSummary: components["schemas"]["AuditFields"] & {
            id: number;
            name: string;
            code: string;
            description: string;
            enabled: boolean;
            menuIds: number[];
        };
        RoleRequest: {
            name: string;
            code: string;
            description: string;
            enabled: boolean;
            menuIds: number[];
        };
        RolePageResponse: {
            /** @enum {integer} */
            status: 0;
            list: components["schemas"]["RoleSummary"][];
            total: number;
        };
        MenuSummary: components["schemas"]["AuditFields"] & {
            id: number;
            parentId: number;
            name: string;
            code: string;
            path: string;
            icon: string;
            sortOrder: number;
            /** @enum {string} */
            type: "directory" | "menu" | "button";
            enabled: boolean;
        };
        MenuRequest: {
            parentId: number;
            name: string;
            code: string;
            path: string;
            icon: string;
            sortOrder: number;
            /** @enum {string} */
            type: "directory" | "menu" | "button";
            enabled: boolean;
        };
        MenuPageResponse: {
            /** @enum {integer} */
            status: 0;
            list: components["schemas"]["MenuSummary"][];
            total: number;
        };
        DictionarySummary: components["schemas"]["AuditFields"] & {
            id: number;
            type: string;
            label: string;
            value: string;
            sortOrder: number;
            enabled: boolean;
            remark: string;
        };
        DictionaryRequest: {
            type: string;
            label: string;
            value: string;
            sortOrder: number;
            enabled: boolean;
            remark: string;
        };
        DictionaryPageResponse: {
            /** @enum {integer} */
            status: 0;
            list: components["schemas"]["DictionarySummary"][];
            total: number;
        };
    };
    responses: {
        /** @description Global HTTP failure */
        GlobalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Mutation result or business failure */
        MutationResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["IdResponse"] | components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Mutation completed or business failure */
        EmptyResult: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EmptySuccessResponse"] | components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        PageNum: number;
        PageSize: number;
        Keyword: string;
        ResourceId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["GlobalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login succeeded or credentials were rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["GlobalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmptySuccessResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                pageNum?: components["parameters"]["PageNum"];
                pageSize?: components["parameters"]["PageSize"];
                keyword?: components["parameters"]["Keyword"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EmptyResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    listRoles: {
        parameters: {
            query?: {
                pageNum?: components["parameters"]["PageNum"];
                pageSize?: components["parameters"]["PageSize"];
                keyword?: components["parameters"]["Keyword"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePageResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EmptyResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    listMenus: {
        parameters: {
            query?: {
                pageNum?: components["parameters"]["PageNum"];
                pageSize?: components["parameters"]["PageSize"];
                keyword?: components["parameters"]["Keyword"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menu page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuPageResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    createMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    updateMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    deleteMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EmptyResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    listDictionaries: {
        parameters: {
            query?: {
                pageNum?: components["parameters"]["PageNum"];
                pageSize?: components["parameters"]["PageSize"];
                keyword?: components["parameters"]["Keyword"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dictionary page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryPageResponse"];
                };
            };
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    createDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    updateDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryRequest"];
            };
        };
        responses: {
            200: components["responses"]["MutationResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
    deleteDictionary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EmptyResult"];
            401: components["responses"]["GlobalError"];
            404: components["responses"]["GlobalError"];
            500: components["responses"]["GlobalError"];
        };
    };
}
